name: readme-bot

on:
  workflow_dispatch:

jobs:
  run-readme-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.0"

      - name: Debug commit
        run: |
          echo "GITHUB_SHA=$GITHUB_SHA"
          git log -1 --oneline

      - name: Run README Bot
        run: |
          go run ./cmd/readme-bot \
             -owner koh5963 \
             -repo readme-bot \
             -number 1
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
